name: Build Release Binaries

on:
  push:
    tags:
      - "unimorph-cli-v[0-9]+.*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-binaries:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }} -p unimorph-cli

      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../unimorph-${{ github.ref_name }}-${{ matrix.target }}.tar.gz unimorph
          cd ../../..

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../unimorph-${{ github.ref_name }}-${{ matrix.target }}.zip unimorph.exe
          cd ../../..

      - name: Upload to Release (Unix)
        if: runner.os != 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          files: unimorph-${{ github.ref_name }}-${{ matrix.target }}.tar.gz

      - name: Upload to Release (Windows)
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          files: unimorph-${{ github.ref_name }}-${{ matrix.target }}.zip
